feat: union transfer solidity rust example
unionlabs/union pull request #3062
Opened 2024-10-02 22:01 UTC by o-az

2024-10-03 10:41 UTC, cor requested changes

2024-10-03 10:41 UTC, cor commented on docs/src/content/docs/integrations/ucs01/solidity/index.mdx
> +</FileTree>
Link to a repo would be good

2024-10-03 10:41 UTC, cor commented on docs/src/content/docs/integrations/ucs01/solidity/index.mdx
> +USDC faucet: [faucet.circle.com](https://faucet.circle.com)
the wallet will need SepoliaETH to make the transfer

2024-10-03 10:41 UTC, cor commented on docs/src/content/docs/integrations/ucs01/solidity/index.mdx
> +
would be good to note which dependencies they need and how to install them

2024-10-03 21:24 UTC, PablitoAmaral commented
### My Experience:

At the beginning, everything was very well explained. I only needed to do a quick search in the Foundry Book to find the command to start "forge init," since I had never used it before.

Then, I followed all the steps in the "Funding the Wallet" section, but I realized that with the resources I had, I couldn't do much without a Premium RPC.

I encountered this error: error code -32000: insufficient funds for gas * price + value: balance 100000000000000000, queued cost 96746019474142502, tx cost 23809826780771570, overshot 20555846254914072


I made some unnecessary transactions (rookie mistake), but overall, I think everything was very well explained and easy to follow. Great work!

2024-10-04 13:20 UTC, cor approved these changes

2024-10-04 13:20 UTC, merged